// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXc8bDUkMvYhcN41M-50BGzS_HFgxXMWc',
    appId: '1:1020561074920:web:d5cd544052fe6144df375d',
    messagingSenderId: '1020561074920',
    projectId: 'agbebel',
    authDomain: 'agbebel.firebaseapp.com',
    storageBucket: 'agbebel.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfbqEgrJKdY-Jt82d3aefDVeY5NoqjWC4',
    appId: '1:1020561074920:android:2857f61c63220249df375d',
    messagingSenderId: '1020561074920',
    projectId: 'agbebel',
    storageBucket: 'agbebel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5wqtOcSLKdI3J7r7lG-z083MQbuJs2qI',
    appId: '1:1020561074920:ios:e558ab89b3435c13df375d',
    messagingSenderId: '1020561074920',
    projectId: 'agbebel',
    storageBucket: 'agbebel.appspot.com',
    iosBundleId: 'com.example.agbebel',
  );
}
